CREATE TABLE CLIENT
(
	[NUM_CLIENT] INT NOT NULL PRIMARY KEY, 
    [NOM_CLIENT] VARCHAR(50) NULL, 
    [ADRESSE_RUE_CLIENT] VARCHAR(200) NULL, 
    [ADRESSE_CP_CLIENT] CHAR(5) NULL, 
    [ADRESSE_VILLE_CLIENT] VARCHAR(50) NULL, 
    [TELEPHONE_CLIENT] CHAR(10) NULL, 
    [MAIL_CLIENT] VARCHAR(150) NULL
)
