CREATE TABLE RESERVATION
(
	[NUM_RESERVATION] INT NOT NULL PRIMARY KEY, 
    [NUM_ASSURANCE] INT NOT NULL, 
    [NUM_CLIENT] INT NOT NULL, 
    [DATE_RESERVATION] DATE NULL, 
    [DATE_DEBUT_RESERVATION] DATE NULL, 
    [DATE_FIN_RESERVATION] DATE NULL, 
    [MONTANT_RESERVATION] DECIMAL(8, 2) NULL, 
    [FORFAIT_KM] CHAR(10) NULL
)
