CREATE TABLE VEHICULE
(
	[IMMATRICULATION] CHAR(7) NOT NULL PRIMARY KEY, 
    [TYPE_BOITE] VARCHAR(30) NOT NULL, 
    [NUM_MAGASIN] INT NOT NULL, 
    [NOM_CATEGORIE] VARCHAR(30) NOT NULL, 
    [NOM_VEHICULE] VARCHAR(50) NOT NULL, 
    [DESCRIPTION_VEHICULE] VARCHAR(300) NULL, 
    [NOMBRE_PLACES] INT NOT NULL, 
    [PRIX_LOCATION] DECIMAL(5, 2) NOT NULL, 
    [CLIMATISATION] int NOT NULL, 
    [LIEN_PHOTO_URL] VARCHAR(100) NULL
)
